usr/lib/llvm-9/bin/c-index-test
usr/lib/llvm-9/bin/clang-check
usr/lib/llvm-9/bin/clang-cl
usr/lib/llvm-9/bin/clang-extdef-mapping
usr/lib/llvm-9/bin/clang-import-test
usr/lib/llvm-9/bin/clang-offload-bundler
usr/lib/llvm-9/bin/clang-refactor
usr/lib/llvm-9/bin/clang-rename
usr/lib/llvm-9/bin/clang-scan-deps
usr/lib/llvm-9/bin/diagtool
usr/lib/llvm-9/bin/hmaptool
usr/lib/llvm-9/bin/sancov
usr/lib/llvm-9/bin/scan-build
usr/lib/llvm-9/bin/scan-view

usr/bin/c-index-test-9
usr/bin/clang-check-9
usr/bin/clang-cl-9
usr/bin/clang-extdef-mapping-9
usr/bin/clang-import-test-9
usr/bin/clang-offload-bundler-9
usr/bin/clang-refactor-9
usr/bin/clang-rename-9
usr/bin/clang-scan-deps-9
usr/bin/diagtool-9
usr/bin/hmaptool-9
usr/bin/sancov-9
usr/bin/scan-build-9
usr/bin/scan-view-9

usr/lib/llvm-9/libexec/c++-analyzer
usr/lib/llvm-9/libexec/ccc-analyzer

usr/lib/llvm-9/share/clang/clang-rename.el
usr/lib/llvm-9/share/clang/clang-rename.py
usr/lib/llvm-9/share/scan-build/
usr/lib/llvm-9/share/scan-view/
